-- Run this in your Supabase SQL Editor to create the table

create table todos (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  text text not null,
  completed boolean default false,
  status text default 'todo',
  priority text default 'medium',
  due_date text,
  description text,
  comments jsonb default '[]',
  attachments jsonb default '[]'
);
